---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2018/11/16 11:13
---
--可以有分号，也可以没有
print("die") print("die") print("die")
print("die") ; print("die")

--加载其他块
dofile("_1_helloWorld.lua")